version: 2.1

orbs:
  node: circleci/node@6.2.0

parameters:
  node_version:
    type: string
    default: '18.18.2'

commands:
  install_deps:
    steps:
      - node/install-packages:
          pkg-manager: yarn
          cache-version: v1
          cache-only-lockfile: false
          app-dir: ~/repo
          override-ci-command: >
            npx --yes retry-cli -n 5 -t 3000 --
            yarn install --pure-lockfile --ignore-scripts --no-progress

jobs:
  build:
    executor:
      name: node/default
      tag: << pipeline.parameters.node_version >>
    working_directory: ~/repo
    steps:
      - checkout
      - install_deps
      - run: yarn type-check
      - run: yarn lint:ci
      - run: yarn test
